# Generated by Django 5.0.6 on 2024-06-28 02:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egressus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo_de_mensagem', models.IntegerField(choices=[(1, 'Vagas de Emprego'), (2, 'Eventos')])),
                ('data_de_postagem', models.DateTimeField(default=django.utils.timezone.now)),
                ('enviar_para_todos', models.BooleanField(default=False)),
                ('curso_alvo', models.ForeignKey(blank=True, db_column='id_curso', null=True, on_delete=django.db.models.deletion.CASCADE, to='egressus_app.curso')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'managed': True,
            },
        ),
    ]
