# Generated by Django 5.0.7 on 2024-07-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egressus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egressoimagecontent',
            name='egresso',
            field=models.ForeignKey(db_column='id_egresso', on_delete=django.db.models.deletion.CASCADE, to='egressus_app.egressoturma'),
        ),
        migrations.AlterField(
            model_name='egressoturma',
            name='turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.CASCADE, to='egressus_app.turma'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='municipio',
            field=models.ForeignKey(db_column='id_municipio', on_delete=django.db.models.deletion.PROTECT, to='egressus_app.municipio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.CASCADE, to='egressus_app.estado'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.PROTECT, to='egressus_app.curso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(db_column='id_escola', on_delete=django.db.models.deletion.PROTECT, to='egressus_app.escola'),
        ),
        migrations.AlterField(
            model_name='turmaimagecontent',
            name='turma',
            field=models.ForeignKey(db_column='id_turma', on_delete=django.db.models.deletion.CASCADE, to='egressus_app.turma'),
        ),
    ]
